In [1]:
pip install numpy


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [7]:
random_int_array1 = np.random.randint(1, 50, size=(10))
random_int_array1 

array([36, 34,  2, 21, 22,  1, 38, 20, 39, 20])

In [9]:
random_int_array1.size

10

In [10]:
random_int_array1.dtype


dtype('int32')

In [11]:
random_int_array1.ndim


1

In [14]:
random_int_array = np.random.randint(1, 100, size=(2, 5))
random_int_array

array([[13,  4, 93, 74, 85],
       [24, 66, 83, 94,  1]])

In [15]:
random_int_array.shape

(2, 5)

In [17]:
np.mean(random_int_array1)

23.3

In [18]:
random_int_array12 = np.random.randint(1, 50, size=(20))
np.mean(random_int_array12)

20.95

In [19]:
a = np.random.randint(1, 10, size=(3, 3))
b= np.random.randint(1, 100, size=(3, 3))
np.add(a,b)

array([[83,  8, 74],
       [70, 17, 97],
       [32, 97, 38]])

In [20]:
x = np.add(a,b)
np.mean(x)

57.333333333333336

In [21]:
c = np.random.randint(1, 100, size=(20))
cond = c>50
c[cond]


array([94, 56, 76, 68, 73, 76, 74, 74, 58, 63, 52, 77])

In [22]:
cd = np.random.randint(1, 10, size=(20))
np.random.shuffle(cd)

In [27]:
cd
np.random.shuffle(cd)

In [28]:
np.random.choice(cd , 5)

array([5, 5, 5, 8, 2])

In [ ]:
z = 